-- ============================================================================
-- Internal Messaging: DM conversations between users in the same organization
-- ============================================================================

-- 1. Tables

create table "public"."dm_conversations" (
    "id" bigint generated by default as identity not null primary key,
    "org_type" text not null check (org_type in ('internal', 'portal')),
    "company_id" bigint references companies(id),
    "participant_1_id" uuid not null references auth.users(id),
    "participant_2_id" uuid not null references auth.users(id),
    "last_message_at" timestamptz not null default now(),
    "last_message_preview" text,
    "created_at" timestamptz not null default now(),
    constraint uq_dm_conversation unique (participant_1_id, participant_2_id),
    constraint check_participants check (participant_1_id < participant_2_id)
);
alter table "public"."dm_conversations" enable row level security;

create table "public"."dm_messages" (
    "id" bigint generated by default as identity not null primary key,
    "conversation_id" bigint not null references dm_conversations(id) on delete cascade,
    "sender_id" uuid not null references auth.users(id),
    "body" text not null,
    "created_at" timestamptz not null default now(),
    "read_at" timestamptz
);
alter table "public"."dm_messages" enable row level security;
create index idx_dm_messages_conversation on dm_messages(conversation_id, created_at);

-- 2. Grants

grant select, insert, update on table "public"."dm_conversations" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."dm_conversations" to "service_role";

grant select, insert, update on table "public"."dm_messages" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."dm_messages" to "service_role";

-- 3. RLS Policies

-- dm_conversations: internal users see their own conversations
create policy "Internal DM conversations read" on "public"."dm_conversations"
  as permissive for select to authenticated
  using (
    org_type = 'internal'
    and get_current_user_type() = 'internal'
    and (participant_1_id = auth.uid() or participant_2_id = auth.uid())
  );

create policy "Portal DM conversations read" on "public"."dm_conversations"
  as permissive for select to authenticated
  using (
    org_type = 'portal'
    and get_current_user_type() = 'portal'
    and company_id = get_portal_company_id()
    and (participant_1_id = auth.uid() or participant_2_id = auth.uid())
  );

create policy "Create internal DM conversation" on "public"."dm_conversations"
  as permissive for insert to authenticated
  with check (
    org_type = 'internal'
    and get_current_user_type() = 'internal'
    and (participant_1_id = auth.uid() or participant_2_id = auth.uid())
  );

create policy "Create portal DM conversation" on "public"."dm_conversations"
  as permissive for insert to authenticated
  with check (
    org_type = 'portal'
    and get_current_user_type() = 'portal'
    and company_id = get_portal_company_id()
    and (participant_1_id = auth.uid() or participant_2_id = auth.uid())
  );

create policy "Update internal DM conversation" on "public"."dm_conversations"
  as permissive for update to authenticated
  using (
    org_type = 'internal' and get_current_user_type() = 'internal'
    and (participant_1_id = auth.uid() or participant_2_id = auth.uid())
  );

create policy "Update portal DM conversation" on "public"."dm_conversations"
  as permissive for update to authenticated
  using (
    org_type = 'portal' and get_current_user_type() = 'portal'
    and company_id = get_portal_company_id()
    and (participant_1_id = auth.uid() or participant_2_id = auth.uid())
  );

-- dm_messages: users can read messages in their conversations
create policy "Read own DM messages" on "public"."dm_messages"
  as permissive for select to authenticated
  using (
    exists (
      select 1 from dm_conversations c
      where c.id = conversation_id
      and (c.participant_1_id = auth.uid() or c.participant_2_id = auth.uid())
    )
  );

create policy "Send DM messages" on "public"."dm_messages"
  as permissive for insert to authenticated
  with check (
    sender_id = auth.uid()
    and exists (
      select 1 from dm_conversations c
      where c.id = conversation_id
      and (c.participant_1_id = auth.uid() or c.participant_2_id = auth.uid())
    )
  );

create policy "Mark DM messages read" on "public"."dm_messages"
  as permissive for update to authenticated
  using (
    sender_id != auth.uid()
    and exists (
      select 1 from dm_conversations c
      where c.id = conversation_id
      and (c.participant_1_id = auth.uid() or c.participant_2_id = auth.uid())
    )
  );

-- 4. Trigger to update conversation preview on new message

create function public.update_dm_conversation_on_message()
returns trigger language plpgsql security definer set search_path to 'public' as $$
begin
  update dm_conversations
  set last_message_at = NEW.created_at,
      last_message_preview = left(NEW.body, 100)
  where id = NEW.conversation_id;
  return NEW;
end;
$$;

create trigger trg_dm_message_after_insert
  after insert on dm_messages
  for each row execute function update_dm_conversation_on_message();

-- 5. Enable Supabase Realtime

alter publication supabase_realtime add table dm_messages;
