-- ============================================================================
-- Customer Portal: tables, RLS helper functions, RLS policies, trigger update
-- ============================================================================

-- 1. New Tables (created first — RLS helper functions reference these)

-- Plans: subscription tiers
create table "public"."plans" (
    "id" bigint generated by default as identity not null primary key,
    "name" text not null,
    "stripe_price_id" text,
    "max_seats" integer not null default 5,
    "max_api_calls" integer not null default 1000,
    "max_storage_mb" integer not null default 500,
    "features" jsonb not null default '{}',
    "price_monthly" integer,
    "price_yearly" integer,
    "is_active" boolean not null default true,
    "created_at" timestamptz not null default now()
);
alter table "public"."plans" enable row level security;

-- Portal Users: customer team members (separate from internal sales)
create table "public"."portal_users" (
    "id" bigint generated by default as identity not null primary key,
    "user_id" uuid not null references auth.users(id),
    "company_id" bigint not null references companies(id),
    "first_name" text not null,
    "last_name" text not null,
    "email" text not null,
    "role" text not null default 'member',
    "avatar" jsonb,
    "disabled" boolean not null default false,
    "created_at" timestamptz not null default now()
);
alter table "public"."portal_users" enable row level security;
create unique index uq_portal_users_user_id on portal_users(user_id);

-- Subscriptions: one per company
create table "public"."subscriptions" (
    "id" bigint generated by default as identity not null primary key,
    "company_id" bigint not null references companies(id),
    "plan_id" bigint not null references plans(id),
    "status" text not null default 'active',
    "current_period_start" timestamptz not null default now(),
    "current_period_end" timestamptz not null default (now() + interval '30 days'),
    "stripe_subscription_id" text,
    "created_at" timestamptz not null default now(),
    "updated_at" timestamptz not null default now()
);
alter table "public"."subscriptions" enable row level security;
create unique index uq_subscriptions_company on subscriptions(company_id);

-- Usage Records: consumption tracking
create table "public"."usage_records" (
    "id" bigint generated by default as identity not null primary key,
    "company_id" bigint not null references companies(id),
    "metric" text not null,
    "value" bigint not null default 0,
    "period_start" timestamptz not null,
    "period_end" timestamptz not null,
    "recorded_at" timestamptz not null default now()
);
alter table "public"."usage_records" enable row level security;

-- Product Configs: per-customer Chaster AI agent settings
create table "public"."product_configs" (
    "id" bigint generated by default as identity not null primary key,
    "company_id" bigint not null references companies(id),
    "config" jsonb not null default '{}',
    "updated_at" timestamptz not null default now(),
    "updated_by" bigint references portal_users(id)
);
alter table "public"."product_configs" enable row level security;
create unique index uq_product_configs_company on product_configs(company_id);

-- Chat Widget Configs: per-customer widget appearance/behavior
create table "public"."chat_widget_configs" (
    "id" bigint generated by default as identity not null primary key,
    "company_id" bigint not null references companies(id),
    "config" jsonb not null default '{}',
    "updated_at" timestamptz not null default now(),
    "updated_by" bigint references portal_users(id)
);
alter table "public"."chat_widget_configs" enable row level security;
create unique index uq_chat_widget_configs_company on chat_widget_configs(company_id);

-- Conversations: GDPR-protected chat transcripts (customer-only access)
create table "public"."conversations" (
    "id" bigint generated by default as identity not null primary key,
    "company_id" bigint not null references companies(id),
    "visitor_id" text,
    "visitor_name" text,
    "visitor_email" text,
    "messages" jsonb not null default '[]',
    "status" text not null default 'open',
    "metadata" jsonb not null default '{}',
    "created_at" timestamptz not null default now(),
    "updated_at" timestamptz not null default now()
);
alter table "public"."conversations" enable row level security;

-- 2. RLS Helper Functions

create function public.get_current_user_type()
returns text
language sql
security definer
stable
set search_path to 'public'
as $$
  select case
    when exists (select 1 from sales where user_id = auth.uid()) then 'internal'
    when exists (select 1 from portal_users where user_id = auth.uid()) then 'portal'
    else 'anonymous'
  end;
$$;

create function public.get_portal_company_id()
returns bigint
language sql
security definer
stable
set search_path to 'public'
as $$
  select company_id from portal_users where user_id = auth.uid() limit 1;
$$;

create function public.is_portal_admin()
returns boolean
language sql
security definer
stable
set search_path to 'public'
as $$
  select exists (
    select 1 from portal_users
    where user_id = auth.uid() and role = 'admin' and disabled = false
  );
$$;

-- 3. Grants for new tables

grant select on table "public"."plans" to "authenticated";
grant select on table "public"."plans" to "service_role";
grant insert, update, delete on table "public"."plans" to "service_role";

grant select, insert, update, delete on table "public"."portal_users" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."portal_users" to "service_role";

grant select, insert, update, delete on table "public"."subscriptions" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."subscriptions" to "service_role";

grant select, insert, update, delete on table "public"."usage_records" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."usage_records" to "service_role";

grant select, insert, update, delete on table "public"."product_configs" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."product_configs" to "service_role";

grant select, insert, update, delete on table "public"."chat_widget_configs" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."chat_widget_configs" to "service_role";

grant select, insert, update, delete on table "public"."conversations" to "authenticated";
grant select, insert, update, delete, references, trigger, truncate on table "public"."conversations" to "service_role";

-- 4. RLS Policies for NEW tables

-- Plans: readable by all authenticated users (public catalog)
create policy "Plans readable by all" on "public"."plans"
  as permissive for select to authenticated using (true);

-- Portal Users: see own company + internal sees all
create policy "Portal users read own company" on "public"."portal_users"
  as permissive for select to authenticated
  using (
    company_id = get_portal_company_id()
    or get_current_user_type() = 'internal'
  );

create policy "Portal admins manage own company users" on "public"."portal_users"
  as permissive for insert to authenticated
  with check (
    (company_id = get_portal_company_id() and is_portal_admin())
    or get_current_user_type() = 'internal'
  );

create policy "Portal admins update own company users" on "public"."portal_users"
  as permissive for update to authenticated
  using (
    (company_id = get_portal_company_id() and is_portal_admin())
    or get_current_user_type() = 'internal'
  )
  with check (
    (company_id = get_portal_company_id() and is_portal_admin())
    or get_current_user_type() = 'internal'
  );

create policy "Portal admins delete own company users" on "public"."portal_users"
  as permissive for delete to authenticated
  using (
    (company_id = get_portal_company_id() and is_portal_admin())
    or get_current_user_type() = 'internal'
  );

-- Subscriptions: portal sees own company, internal sees all
create policy "Subscription read access" on "public"."subscriptions"
  as permissive for select to authenticated
  using (
    company_id = get_portal_company_id()
    or get_current_user_type() = 'internal'
  );

create policy "Subscription write internal only" on "public"."subscriptions"
  as permissive for insert to authenticated
  with check (get_current_user_type() = 'internal');

create policy "Subscription update internal only" on "public"."subscriptions"
  as permissive for update to authenticated
  using (get_current_user_type() = 'internal')
  with check (get_current_user_type() = 'internal');

-- Usage Records: portal sees own company, internal sees all
create policy "Usage read access" on "public"."usage_records"
  as permissive for select to authenticated
  using (
    company_id = get_portal_company_id()
    or get_current_user_type() = 'internal'
  );

create policy "Usage write internal only" on "public"."usage_records"
  as permissive for insert to authenticated
  with check (get_current_user_type() = 'internal');

-- Product Configs: portal sees/edits own company, internal sees all
create policy "Product config read access" on "public"."product_configs"
  as permissive for select to authenticated
  using (
    company_id = get_portal_company_id()
    or get_current_user_type() = 'internal'
  );

create policy "Product config write access" on "public"."product_configs"
  as permissive for insert to authenticated
  with check (
    (company_id = get_portal_company_id() and is_portal_admin())
    or get_current_user_type() = 'internal'
  );

create policy "Product config update access" on "public"."product_configs"
  as permissive for update to authenticated
  using (
    (company_id = get_portal_company_id() and is_portal_admin())
    or get_current_user_type() = 'internal'
  )
  with check (
    (company_id = get_portal_company_id() and is_portal_admin())
    or get_current_user_type() = 'internal'
  );

-- Chat Widget Configs: portal sees/edits own, internal can see (not private data)
create policy "Widget config read access" on "public"."chat_widget_configs"
  as permissive for select to authenticated
  using (
    company_id = get_portal_company_id()
    or get_current_user_type() = 'internal'
  );

create policy "Widget config write access" on "public"."chat_widget_configs"
  as permissive for insert to authenticated
  with check (
    (company_id = get_portal_company_id() and is_portal_admin())
    or get_current_user_type() = 'internal'
  );

create policy "Widget config update access" on "public"."chat_widget_configs"
  as permissive for update to authenticated
  using (
    (company_id = get_portal_company_id() and is_portal_admin())
    or get_current_user_type() = 'internal'
  )
  with check (
    (company_id = get_portal_company_id() and is_portal_admin())
    or get_current_user_type() = 'internal'
  );

-- Conversations: GDPR-PROTECTED — customer-only, internal admins BLOCKED
create policy "Conversations customer only read" on "public"."conversations"
  as permissive for select to authenticated
  using (company_id = get_portal_company_id());

create policy "Conversations customer only insert" on "public"."conversations"
  as permissive for insert to authenticated
  with check (company_id = get_portal_company_id());

create policy "Conversations customer only update" on "public"."conversations"
  as permissive for update to authenticated
  using (company_id = get_portal_company_id())
  with check (company_id = get_portal_company_id());

-- 5. RESTRICTIVE RLS on existing CRM tables — blocks portal users

-- Companies: internal users get full access; portal users can only read their own company
create policy "Internal only write" on "public"."companies"
  as restrictive for insert to authenticated
  with check (get_current_user_type() = 'internal');

create policy "Internal only update" on "public"."companies"
  as restrictive for update to authenticated
  using (get_current_user_type() = 'internal')
  with check (get_current_user_type() = 'internal');

create policy "Internal only delete" on "public"."companies"
  as restrictive for delete to authenticated
  using (get_current_user_type() = 'internal');

create policy "Companies read own or internal" on "public"."companies"
  as restrictive for select to authenticated
  using (
    get_current_user_type() = 'internal'
    or id = get_portal_company_id()
  );

create policy "Internal only access" on "public"."contacts"
  as restrictive for all to authenticated
  using (get_current_user_type() = 'internal')
  with check (get_current_user_type() = 'internal');

create policy "Internal only access" on "public"."contact_notes"
  as restrictive for all to authenticated
  using (get_current_user_type() = 'internal')
  with check (get_current_user_type() = 'internal');

create policy "Internal only access" on "public"."deals"
  as restrictive for all to authenticated
  using (get_current_user_type() = 'internal')
  with check (get_current_user_type() = 'internal');

create policy "Internal only access" on "public"."deal_notes"
  as restrictive for all to authenticated
  using (get_current_user_type() = 'internal')
  with check (get_current_user_type() = 'internal');

create policy "Internal only access" on "public"."sales"
  as restrictive for all to authenticated
  using (get_current_user_type() = 'internal')
  with check (get_current_user_type() = 'internal');

create policy "Internal only access" on "public"."tags"
  as restrictive for all to authenticated
  using (get_current_user_type() = 'internal')
  with check (get_current_user_type() = 'internal');

create policy "Internal only access" on "public"."tasks"
  as restrictive for all to authenticated
  using (get_current_user_type() = 'internal')
  with check (get_current_user_type() = 'internal');

create policy "Internal only access" on "public"."configuration"
  as restrictive for all to authenticated
  using (get_current_user_type() = 'internal')
  with check (get_current_user_type() = 'internal');

-- 6. Update handle_new_user trigger to route portal users

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
declare
  sales_count int;
  user_type text;
  portal_company_id bigint;
  portal_role text;
begin
  user_type := coalesce(new.raw_user_meta_data ->> 'user_type', 'internal');

  if user_type = 'portal' then
    portal_company_id := (new.raw_user_meta_data ->> 'company_id')::bigint;
    portal_role := coalesce(new.raw_user_meta_data ->> 'portal_role', 'member');

    insert into public.portal_users (first_name, last_name, email, user_id, company_id, role)
    values (
      coalesce(new.raw_user_meta_data ->> 'first_name', ''),
      coalesce(new.raw_user_meta_data ->> 'last_name', ''),
      new.email,
      new.id,
      portal_company_id,
      portal_role
    );
  else
    select count(id) into sales_count from public.sales;

    insert into public.sales (first_name, last_name, email, user_id, administrator)
    values (
      new.raw_user_meta_data ->> 'first_name',
      new.raw_user_meta_data ->> 'last_name',
      new.email,
      new.id,
      case when sales_count > 0 then FALSE else TRUE end
    );
  end if;

  return new;
end;
$$;

-- Update handle_update_user to also handle portal users
create or replace function public.handle_update_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  -- Try updating sales first
  update public.sales
  set
    first_name = new.raw_user_meta_data ->> 'first_name',
    last_name = new.raw_user_meta_data ->> 'last_name',
    email = new.email
  where user_id = new.id;

  -- If no sales row matched, try portal_users
  if not found then
    update public.portal_users
    set
      first_name = coalesce(new.raw_user_meta_data ->> 'first_name', first_name),
      last_name = coalesce(new.raw_user_meta_data ->> 'last_name', last_name),
      email = new.email
    where user_id = new.id;
  end if;

  return new;
end;
$$;

-- 7. Seed default plans
insert into "public"."plans" (name, max_seats, max_api_calls, max_storage_mb, features, price_monthly, price_yearly) values
  ('Starter', 3, 1000, 500, '{"ai_agents": 1, "custom_branding": false, "analytics": "basic"}', 2900, 29000),
  ('Pro', 10, 10000, 2000, '{"ai_agents": 5, "custom_branding": true, "analytics": "advanced", "priority_support": true}', 7900, 79000),
  ('Enterprise', 50, 100000, 10000, '{"ai_agents": -1, "custom_branding": true, "analytics": "advanced", "priority_support": true, "sla": true, "dedicated_account_manager": true}', 19900, 199000);
